### ISSUE TITLE
Child bindings not used to resolve bindings registered on the parent

### ISSUE THREAD

**Issue by binary-koan** [pcafstockf/async-injection#11]
Note: I'm pretty new to DI; this may be entirely expected behaviour or I may be thinking about it the wrong way, it just seemed a little counterintuitive to me!

Basically, I'm trying to use this alongside MikroORM, which expects you to create a new "entity manager" object for each request. I assumed I could do something like

```ts
@Injectable()
class SomeClassUsingOrm {
  constructor(private readonly entityManager: EntityManager) {}
}

rootContainer.bindClass(SomeClassUsingOrm)

// on each request
const child = new Container(rootContainer)
child.bindFactory(EntityManager, () => makeNewEntityManager()).asSingleton()

console.log(child.get(SomeClassUsingOrm)) // expecting this to use the factory from the child
```

However, this gives a `Error: Symbol not bound: class EntityManager` error. It seems like because I used `bindClass` on the parent, the `EntityManager` parameter will only be resolved with the parent's providers and will ignore anything added to the child.

My goal here is to have a "abstract container" with a set of classes that depend on an type I can't yet construct. Or, to put it another way, I want a singleton factory that's called exactly once _per clone_ of the parent container.

**Comment by pcafstockf** [comment]
An "abstract container" is an interesting idea, however I'm not aware of any DI system on any language/platform that implements such a thing, so I'm a little reluctant to pursue that ATM.

However, you mention "clone" as an alternative type approach, and there are some DI systems that support that.  
It could also be useful for unit testing (the ability to set up a baseline container which a unit test can "alter" without side effects on other tests).

A partially configured container (e.g. abstract) being used at runtime just feels wrong to me, but I think a clone and extend approach should address your use case, and I could pretend it was just for unit testing :-)

Clone is also easy enough that I can bump this to the top of the ToDo list and should be able to get something out in the next week or two.

If you need something before then, this is a little hacky, but I think it should work until I get a real clone operation in place:
```
class ContainerClone extends Container {
	constructor(src: Container) {
		super((src as ContainerClone).parent);
		this.providers = new Map<InjectableId<any>, Provider>((src as ContainerClone).providers);
	}
}
```

**Comment by binary-koan** [comment]
Hmm, that gives the same error. I believe it's because when `bindClass` is called, the current `this` (i.e. parent container) is bound to the `stateResolver` closure here:

https://github.com/pcafstockf/async-injection/blob/4ffb6c095f8de6726ded4718d27f7c12f60b3ab6/src/container.ts#L115-L116

So even though the clone/subclass has a new `providers` object with the new dependency, the provider itself is the same object with the same `this` binding.

To illustrate the problem, it works by modifying `ContainerClone` with a hack like this:

```ts
class ContainerClone extends Container {
  constructor(src: Container) {
    super((src as ContainerClone).parent)
    this.providers = new Map<InjectableId<any>, Provider>((src as ContainerClone).providers)

    for (const [id, provider] of this.providers.entries()) {
      // stateResolver = this is a ClassBasedProvider (not exported, so no instanceof)
      if ((provider as any).stateResolver) {
        const clone = Object.assign(Object.create(Object.getPrototypeOf(provider)), provider)

        clone.stateResolver = (i: InjectableId<any>) => {
          return this.resolveState(i)
        }

        this.providers.set(id, clone)
      }
    }
  }
}
```

(I guess that might make cloning a harder feature to implement - I'd be happy to open a PR with an improved version of this approach, but I feel like there's a nicer way of approaching it that I'm missing ...)

**Comment by pcafstockf** [comment]
@binary-koan nice catch!  Thanks.
I've looked a little deeper based on your feedback and there is also a reference used by the success and error handlers.  Not everybody uses those, but they are still part of the library :-) 
PR's are always welcome, but since I will need to refactor the other references, probably easier if I address the stateResolver at the same time.
I have some other commitments this weekend but will make sure I get this fixed next weekend.
If you don't use success and error handlers, it seems to me that your example above would work as a temporary patch.

**Comment by pcafstockf** [comment]
@binary-koan 
Borrowed some of your ideas and code, did a little refactoring on the library, and implemented an experimental clone method on Container (along with tests).  
If you want to use it, please carefully read the comments/caveats on the Container.clone method.  Also, any thoughts or suggested edits are always appreciated.  
Thanks for raising the issue.

**Comment by binary-koan** [comment]
@pcafstockf Awesome, thanks heaps for adding that! The explanation of caveats is really useful, and it's working perfectly for my use case. Will let you know if I run into any issues
