### ISSUE TITLE
Could not find a declaration file for module 'async-injection'

### ISSUE THREAD

**Issue by IvanLi-CN** [pcafstockf/async-injection#18]
When I upgraded to async-injection v2.0 and tried to build my project using `tsc`, I encountered the following error:

```shell
error TS7016: Could not find a declaration file for module 'async-injection'. <project_root>/node_modules/.pnpm/async-injection@2.0.0/node_modules/async-injection/lib/esm/index.js' implicitly has an 'any' type.
There are types at '<project_root>/packages/world/node_modules/async-injection/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'async-injection' library may need to update its package.json or typings.
```

I attempted to resolve this by modifying the `exports` field in `async-injection/package.json` to the following:

```json
	"exports": {
		".": {
			"import": "./lib/esm/index.js",
			"require": "./lib/cjs/index.js",
			"types": "./lib/index.d.ts"
		},
		"./*": {
			"import": "./lib/esm/*.js",
			"require": "./lib/cjs/*.js",
			"types": "./lib/*.d.ts"
		}
	},
```

After this modification, I was able to build successfully. I'm not entirely sure what happened, but this change resolved the issue I was facing.

## Environment Information

```shell
typescript: 5.6.2
pnpm: 9.10.0
node: 20.17.0
macOS: 14.6.1
```

**Comment by pcafstockf** [comment]
Thank you for finding the problem and the fix.

Rather embarrassed I did not see that 😊 
Pushing a release now.

**Comment by IvanLi-CN** [comment]
Thank you for promptly resolving the issue! I’ve updated to the new version, and it works great.
