### ISSUE TITLE
Remove `reflect-metadata` from dependencies.

### ISSUE THREAD

**Issue by tripodsgames** [pcafstockf/async-injection#4]
In my project im using `@abraham/reflection`, i want to keep it and use this package as well, its possible to remove `reflect-metadata` and let the user select the reflection polyfill?

**Comment by pcafstockf** [comment]
`async-injection` relies heavily on `Reflect.construct`, and looking at the readme for `@abraham/reflection`, it does not seem to support that particular function (although it does support all the other Reflect API's that `async-injection` uses).

If you have a suggestion for addressing that, I'm open to the idea of supporting a user selected polyfill for Reflect.

**Comment by tripodsgames** [comment]
> `async-injection` relies heavily on `Reflect.construct`, and looking at the readme for `@abraham/reflection`, it does not seem to support that particular function (although it does support all the other Reflect API's that `async-injection` uses).
> 
> If you have a suggestion for addressing that, I'm open to the idea of supporting a user selected polyfill for Reflect.


https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct
`Reflect.construct` is available on the native Reflect API, its not implemented on `reflect-metadata`.

**Comment by tripodsgames** [comment]
@pcafstockf
If you want, i can make the pr when i have some time

**Comment by pcafstockf** [comment]
> Reflect.construct is available on the native Reflect API
:blush: Right you are sir.  I should have looked at that more closely.

A PR would be great.
