### ISSUE TITLE
Add clone method to the container.

### ISSUE THREAD

**Issue by tripodsgames** [pcafstockf/async-injection#7]
Add an option to clone the container.

Example:
For each request in a server, clone the container for specific request binds.

```typescript
const container = new Container();

container.bind(ExampleRepository).asSingleton();

app.use((req, res, next) => {
    req.container = container.clone();
    // Just an Example.
    req.container.bindFactory(Request, () => req).asSingleton();
    req.container.bindFactory(Response, () => res).asSingleton();
});
```

@pcafstockf i can make the pull request if you like the idea.

**Comment by pcafstockf** [comment]
This specific use case can more reliably and efficiently be handled using the hierarchical containers functionality.

```
const container = new Container();

container.bind(ExampleRepository).asSingleton();

app.use((req, res, next) => {
    req.container = new Container(container);
    // Just an Example.
    req.container.bindFactory(Request, () => req).asSingleton();
    req.container.bindFactory(Response, () => res).asSingleton();
});
```

Let me know if I misunderstood you request or if there is a more problematic use case.

**Comment by tripodsgames** [comment]
> This specific use case can more reliably and efficiently be handled using the hierarchical containers functionality.
> 
> ```
> const container = new Container();
> 
> container.bind(ExampleRepository).asSingleton();
> 
> app.use((req, res, next) => {
>     req.container = new Container(container);
>     // Just an Example.
>     req.container.bindFactory(Request, () => req).asSingleton();
>     req.container.bindFactory(Response, () => res).asSingleton();
> });
> ```
> 
> Let me know if I misunderstood you request or if there is a more problematic use case.

This is exactly what i need.
